theme: jekyll-theme-minimal
title: ğŸ‘»ğŸ•¸ï¸ğŸƒ
description: Vasyl Tkachenko CV
favicon: /assets/logo.svg
email: vasyltkachenko07@gmail.com  
github_link: https://github.com/vsltkachenko
linkedin: https://www.linkedin.com/in/vsltkachenko
